require: rubocop-rails
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'coverage/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'spec/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - './*'
    - 'sandbox/**/*'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Rails/UniqueValidationWithoutIndex:
  Enabled: false
